# Generated by Django 5.1.7 on 2025-03-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributer_publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('date_of_publish', models.DateField()),
                ('narrator', models.CharField(max_length=50)),
                ('describtion', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='persian', max_length=100)),
                ('volume', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks_authors', to='contributer_publisher.contributers')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks_publishers', to='contributer_publisher.publishers')),
            ],
        ),
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('time_to_read', models.DurationField()),
                ('date_of_publish', models.DateField()),
                ('describtion', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='persian', max_length=100)),
                ('volume', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks_authors', to='contributer_publisher.contributers')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_books_publishers', to='contributer_publisher.publishers')),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('time_to_read', models.DurationField()),
                ('date_of_publish', models.DateField()),
                ('describtion', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='persian', max_length=100)),
                ('volume', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_authors', to='contributer_publisher.contributers')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_publishers', to='contributer_publisher.publishers')),
            ],
        ),
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('time_to_read', models.DurationField()),
                ('date_of_publish', models.DateField()),
                ('describtion', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='persian', max_length=100)),
                ('volume', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazines_authors', to='contributer_publisher.contributers')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazines_publishers', to='contributer_publisher.publishers')),
            ],
        ),
    ]
